src/money_utils/report/urls.py
from django.urls import path

from . import views

app_name = "report"

urlpatterns = [
    path("", views.index, name="index"),
    path("drinks/", views.drinks, name="drinks"),
    path("members_per_month/", views.members_per_month, name="members_per_month"),
    path("member_report/", views.member_report_view, name="member_report"),
    path("recharges.json", views.recharges, name="recharges"),
    path("tan", views.admin_tan, name="tan"),
]

src/money_utils/webreport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/uwsgi/", include("django_uwsgi.urls")),
    path("admin/", admin.site.urls),
    path("", include("money_utils.report.urls")),
]

src/money_utils/report/models.py
import logging
from _sha256 import sha256

import mt940
from django.db import models
from django.db.models import UniqueConstraint

from ..schema.fee_util import DetectMethod, PayInterval
from ..schema.transaction import TxType, copy_fields, optional_fields, empty_fields

# from money_utils import get_config

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


def choice_from_enum(enum):
    return [(v.name, v.name.lower().capitalize()) for v in enum]


class FeeEntry(models.Model):
    id = models.CharField(max_length=255, primary_key=True)

    member = models.ForeignKey("Member", models.DO_NOTHING)
    month = models.DateField()
    pk = UniqueConstraint(
        fields=["member", "month"], name="fee_entry_member_id_month_966eb854_uniq"
    )

    tx = models.ForeignKey("Transaction", on_delete=models.DO_NOTHING)
    fee = models.DecimalField(decimal_places=2, max_digits=10)
    pay_interval = models.TextField(choices=choice_from_enum(PayInterval))

    detect_method = models.TextField(
        choices=choice_from_enum(DetectMethod),
        default=DetectMethod.FALLBACK,
        null=False,
    )

    class Meta:
        managed = True
        db_table = "fee_entry"
        unique_together = (("member", "month"),)

    def save(self, *args, **kwargs):
        self.id = "{}|{}".format(self.member.id, self.month)
        super().save(*args, **kwargs)

    def __str__(self):
        return (
            f"Fee {self.month:%Y-%m} {self.member.id:3} "
            + f"detect={self.detect_method:10} interval={self.pay_interval:10} "
            + f"{self.tx.tx_id[:8]}"
        )


class Member(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    nick = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    email = models.TextField(blank=True, null=True)

    entry_date = models.DateField(blank=True, null=True)
    exit_date = models.DateField(blank=True, null=True)
    pay_interval = models.TextField(choices=choice_from_enum(PayInterval))

    last_fee = models.DecimalField(
        blank=True, null=True, decimal_places=2, max_digits=10
    )
    fee = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=10)

    class Meta:
        managed = True
        db_table = "member"

    def is_member(self):
        return not self.exit_date

    def __str__(self):
        return " ".join(
            [self.first_name, self.last_name, "(%s)" % self.nick if self.nick else ""]
        )


class Status(models.Model):
    key = models.CharField(primary_key=True, max_length=255)
    value_str = models.TextField(blank=True, null=True)
    value_dt = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "status"


class Transaction(models.Model):
    tx_id = models.CharField(primary_key=True, max_length=255)

    member = models.ForeignKey(
        Member, on_delete=models.DO_NOTHING, blank=True, null=True
    )
    type = models.TextField(blank=True, null=True, choices=choice_from_enum(TxType))

    import_date = models.DateTimeField(auto_now_add=True)

    amount = models.DecimalField(decimal_places=2, max_digits=10)

    status = models.TextField(blank=True, null=True)
    funds_code = models.TextField(blank=True, null=True)
    bank_type_id = models.TextField(blank=True, null=True)
    customer_reference = models.TextField(blank=True, null=True)
    bank_reference = models.TextField(blank=True, null=True)
    extra_details = models.TextField(blank=True, null=True)
    currency = models.TextField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    entry_date = models.DateField(blank=True, null=True)
    transaction_code = models.TextField(blank=True, null=True)
    posting_text = models.TextField(blank=True, null=True)
    prima_nota = models.TextField(blank=True, null=True)
    purpose = models.TextField()
    applicant_bin = models.TextField(blank=True, null=True)
    applicant_iban = models.TextField(blank=True, null=True)
    applicant_name = models.TextField(blank=True, null=True)
    return_debit_notes = models.TextField(blank=True, null=True)
    recipient_name = models.TextField(blank=True, null=True)
    additional_purpose = models.TextField(blank=True, null=True)
    gvc_applicant_iban = models.TextField(blank=True, null=True)
    gvc_applicant_bin = models.TextField(blank=True, null=True)
    end_to_end_reference = models.TextField(blank=True, null=True)
    additional_position_reference = models.TextField(blank=True, null=True)
    applicant_creditor_id = models.TextField(blank=True, null=True)
    purpose_code = models.TextField(blank=True, null=True)
    additional_position_date = models.TextField(blank=True, null=True)
    deviate_applicant = models.TextField(blank=True, null=True)
    deviate_recipient = models.TextField(blank=True, null=True)
    frst_one_off_recc = models.TextField(
        db_column="FRST_ONE_OFF_RECC", blank=True, null=True
    )  # Field name made lowercase.
    old_sepa_ci = models.TextField(
        db_column="old_SEPA_CI", blank=True, null=True
    )  # Field name made lowercase.
    old_sepa_additional_position_reference = models.TextField(
        db_column="old_SEPA_additional_position_reference", blank=True, null=True
    )  # Field name made lowercase.
    settlement_tag = models.TextField(blank=True, null=True)
    debitor_identifier = models.TextField(blank=True, null=True)
    compensation_amount = models.TextField(blank=True, null=True)
    original_amount = models.DecimalField(decimal_places=2, max_digits=10, null=True)

    class Meta:
        managed = True
        db_table = "transaction"

    def save(self, *args, **kwargs):
        self.tx_id = self.gen_id()
        super().save(*args, **kwargs)

    def gen_id(self):
        # hash together as much as possible
        # there are NO unique transaction IDs in hbci...
        raw = "|".join(
            [
                str(self.date),
                str(self.entry_date),
                str(self.applicant_bin),
                str(self.applicant_iban),
                str(self.amount),
                str(self.transaction_code),
                str(self.bank_type_id),
                str(self.status),
                str(self.prima_nota),
                str(self.purpose),
            ]
        )
        sha = sha256(raw.encode("UTF8"))
        return sha.hexdigest()

    @classmethod
    def from_sepa(cls, hbci_tx: mt940.models.Transaction):
        data = hbci_tx.data
        tx = Transaction()
        tx.amount = data["amount"].amount

        for key in copy_fields:
            if config.debug:
                if key not in data and key not in optional_fields:
                    logging.error("Putting key %s in optional fields list", key)
                    optional_fields.append(key)
            if key not in optional_fields:
                value = data[key]
            else:
                value = data[key] if key in data else None
            tx.__dict__[key] = value

        for key in empty_fields:
            if tx.__dict__[key] is None:
                tx.__dict__[key] = ""

        return tx

    def __str__(self) -> str:
        return "Tx[from: '{sender}', purpose: '{purpose}', amount: {amount:.2f}, date: {date}]".format(
            sender=self.applicant_name,
            purpose=self.purpose,
            amount=self.amount,
            date=self.date,
        )

src/money_utils/report/views.py
import re
from io import StringIO
import logging

import pandas
from bokeh import embed, resources
from bokeh.models import Range1d, LinearAxis, LabelSet, ColumnDataSource
from bokeh.plotting import figure
from django.db.models import Q, Count, Avg
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.utils import timezone
from django.utils.datetime_safe import datetime
from django.utils.safestring import mark_safe

from ..bank.models import TanRequest
from .get_recharges import get_recharges
from .models import Transaction, FeeEntry

from .members import main as members_main


def index(request):
    return render(request, "index.html", {})


def drinks(request: HttpRequest):
    txs = drinks_transactions()
    sum = 0
    dates = []
    sums = []
    txs_transformed = []
    for tx in txs:
        sum += tx.amount
        dates.append(tx.date)
        sums.append(float(sum))
        txs_transformed.append(
            {
                "sum": sum,
                "date": tx.date.isoformat(),
                "amount": tx.amount,
                "purpose": tx.purpose,
                "applicant": tx.applicant_name,
            }
        )
    # logging.debug("txs: %s", txs_transformed)
    # logging.debug("sums: %s", sums)
    p1: Figure = figure(x_axis_type="datetime", title="Getränkeverkauf")
    p1.sizing_mode = "scale_width"
    p1.height = 300
    p1.grid.grid_line_alpha = 0.3
    p1.xaxis.axis_label = "Datum"
    p1.yaxis.axis_label = "Summe"

    p1.step(dates, sums, color="#22aa22", legend_label="Summe", line_width=3)
    # p1.line([dates[0], dates[-1]], [0, 0], color='#aa0000', line_width=1)
    # p1.legend.location = "top_left"

    html = embed.file_html(p1, resources.CDN, "Getränkeverkauf")
    context = {
        "html": mark_safe(html),
        "txs": txs_transformed if request.user.is_staff else None,
    }
    return render(request, "drinks.html", context)


def drinks_transactions():
    tx = Transaction.objects.filter(
        Q(purpose__contains="edeka")
        | Q(applicant_name__contains="edeka")
        | Q(purpose__startswith="drinks ")
        | Q(purpose__contains="sb-einzahlung")
        | Q(purpose__contains="UNGEZaeHLTES KLEINGELD")
        | Q(purpose__contains="EINNAHMEN GETRAENKEVERKAUF")
    ).order_by("date")
    return tx


def members_per_month(request: HttpRequest):
    members_per_month = (
        FeeEntry.objects.values("month")
        .order_by("month")
        .annotate(count=Count("month"))
    )
    df_members = pandas.DataFrame.from_dict(members_per_month)
    df_members["month"] = df_members["month"].map(lambda m: m.strftime("%Y-%m"))
    df_members["count_text"] = df_members["count"].map(lambda p: "{:.0f}".format(p))

    df_members = df_members.iloc[1:-1]

    member_fees = (
        FeeEntry.objects.values("month").order_by("month").annotate(fee=Avg("fee"))
    )
    df_fees = pandas.DataFrame.from_dict(member_fees)
    df_fees["fee"] = df_fees["fee"].astype(float)
    df_fees["month"] = df_fees["month"].map(lambda m: m.strftime("%Y-%m"))
    df_fees["fee_text"] = df_fees["fee"].map(lambda p: "{:.0f}".format(p))

    p1: Figure = figure(
        title="Member pro Monat",
        x_range=df_members["month"],
        tooltips=[("Monat", "@month"), ("Anzahl", "@count")],
        height=300,
    )
    p1.sizing_mode = "scale_width"

    p1.step(
        x="month",
        color="navy",
        line_width=3,
        source=df_members,
        y="count",
        legend_label="Count of Members (paid fees)",
    )

    p1.extra_y_ranges = {
        "fee_range": Range1d(start=0, end=df_fees["fee"].astype(float).max() + 5)
    }
    p1.add_layout(LinearAxis(y_range_name="fee_range"), "right")
    p1.step(
        x="month",
        y="fee",
        color="firebrick",
        source=df_fees,
        line_width=2,
        y_range_name="fee_range",
        legend_label="Average Fee per member",
    )

    labels = LabelSet(
        x="month",
        y="fee",
        text="fee_text",
        level="glyph",
        x_offset=-10,
        y_offset=10,
        source=ColumnDataSource(df_fees),
        text_font_size="9pt",
        y_range_name="fee_range",
    )
    p1.add_layout(labels)

    labels = LabelSet(
        x="month",
        y="count",
        text="count_text",
        level="glyph",
        x_offset=-15,
        y_offset=10,
        source=ColumnDataSource(df_members),
        text_font_size="9pt",
    )
    p1.add_layout(labels)

    p1.y_range.start = 0
    p1.y_range.end = df_members["count"].max() + 4
    p1.x_range.range_padding = 0.1
    p1.xaxis.axis_label = "Monat"
    p1.xaxis.major_label_orientation = 1.2
    # p1.outline_line_color = None
    p1.legend.location = "bottom_right"

    html = embed.file_html(p1, resources.CDN, "Member pro Monat")

    return render(request, "graph.html", {"html": mark_safe(html)})


def member_report_view(request: HttpRequest):
    if not request.user.is_superuser:
        return HttpResponseRedirect("/admin/login")

    output = StringIO()
    members_main([], to=output, months=36)
    output = output.getvalue()
    return render(request, "member_report.html", {"report": mark_safe(output)})


# @basicauth(realm="Parole?")


def recharges(request: HttpRequest):
    all = get_recharges()
    logging.info("recharge JSON: %s", all)
    return JsonResponse(all)


def admin_tan(request: HttpRequest):
    if not request.user.is_superuser:
        return HttpResponseRedirect("/admin/login")

    if "action" in request.POST and request.POST["action"] == "number":
        return JsonResponse({"number": TanRequest.active_requests().count()})

    if "tan" in request.POST:
        tan = request.POST["tan"]
        date = request.POST["date"]
        tan = re.sub(r"[^a-zA-Z0-9]", "", tan)
        tan_request = TanRequest.objects.get(
            pk=datetime.fromtimestamp(float(date), tz=timezone.utc)
        )
        if tan_request.answer or tan_request.expired:
            return render(request, "admin_tan.html", {"error": "TAN request expired"})
        tan_request.answer = tan
        tan_request.save()

        return render(request, "admin_tan.html", {"tan": tan})

    tan_request = TanRequest.active_request()
    return render(
        request,
        "admin_tan.html",
        {
            "tan_request": tan_request,
            "id": tan_request.date.timestamp() if tan_request else None,
        },
    )

src/money_utils/report/templates/admin_tan.html
{% include 'nav.html' %}
<style>
    .error {
        color: #c63232;
    }
</style>

{% if tan_request %}
    <form action="{% url 'report:tan' %}" method="post">
        {% csrf_token %}
        <p class="tan-challenge">{{ tan_request.challenge }}</p>
        <label for="tan">Enter TAN:</label>
        <input type="number" maxlength="10" minlength="6" name="tan"/>
        <input type="hidden" name="date" value="{{ id }}"/>
        <input type="submit"/>
    </form>
{% else %}
    <meta http-equiv="refresh" content="5">
    {% if tan %}
        <p>OK. Processing TAN <b>{{ tan }}</b>.</p>
    {% elif error %}
        <p class="error">{{ error }}</p>
    {% else %}
        <p>Nothing to do.</p>
    {% endif %}
    <form action="{% url 'report:tan' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Reload"/>
    </form>
{% endif %}

src/money_utils/report/templates/drinks.html
<style>
    td.date {
        width: 5em;
    }

    table thead th {
        border-bottom: 1px solid #000;
    }

    table tr:nth-child(2n) td {
        background-color: #eee;
    }
</style>

{% include 'nav.html' %}

{{ html }}

{% if txs %}
<table>
    <thead>
        <tr>
            <th>Datum</th>
            <th>Betrag</th>
            <th>Summe</th>
            <th>Von/An</th>
            <th>Verwendungszweck</th>
        </tr>
    </thead>
    {% for tx in txs %}
    <tr>
        <td class="date">
            {{ tx.date }}
        </td>
        <td>
            {{ tx.amount }}
        </td>
        <td>
            {{ tx.sum }}
        </td>
        <td>
            {{ tx.applicant }}
        </td>
        <td>
            {{ tx.purpose }}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
(You're not staff, so you don't get the details)
{% endif %}

src/money_utils/report/templates/graph.html
{% include 'nav.html' %}

{{ html }}

src/money_utils/report/templates/index.html
{% include 'nav.html' %}

src/money_utils/report/templates/member_report.html
<style>
    td.date {
        width: 5em;
    }
    table thead th {
        border-bottom: 1px solid #000;
    }
    table tr:nth-child(2n) td {
        background-color: #eee;
    }
</style>

{% include 'nav.html' %}

<pre>
{{ report }}

</pre>

src/money_utils/report/templates/nav.html
<head>
    <style>
        body {
            color: #444444;
            font-family: 'sans-serif';
        }
        nav {
            display: flex;
            width: 100%;
            flex-direction: row;
        }
        nav section {
            margin: .5rem;
            width: 33.3333%;
            display: flex;
            flex-direction: column;
            background-color: #fafafa;
        }
        nav section .section-header {
            text-align: center;
            font-weight: bold;
        }
        nav section a {
            display: block;
            padding: .6rem .1rem;
        }
        nav section a:hover {
            background-color: #ffffff;
            color: #000000;
        }
    </style>
</head>

<nav>

    <section>
        <p class="section-header">main</p>
        {% if user.is_superuser %}
            <a href="{% url 'admin:index' %}">admin</a>
            <a href="/admin/uwsgi">uwsgi</a>
            <a href="{% url 'report:tan' %}">tan <span id="tan_badge"></span></a>
        {% else %}
            <a href="{% url 'admin:login' %}">admin</a>
        {% endif %}
    </section>

    <section>
        <p class="section-header">drinks</p>
        <a href="{% url 'report:drinks' %}">Drinks sales</a>
        <a href="{% url 'report:recharges' %}">Recharges (json)</a>
    </section>

    <section>
        <p class="section-header">members</p>
        <a href="{% url 'report:members_per_month' %}">Members per month</a>
        {% if user.is_superuser %}
            <a href="{% url 'report:member_report' %}">Member Report</a>
        {% endif %}
    </section>
</nav>

{% if user.is_superuser %}
    <script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const tanBadge = document.getElementById('tan_badge');

    async function fetch_now() {
        try {
            const formData = new FormData();
            formData.append('action', 'number')
            const csrftoken = getCookie('csrftoken');
            const response = await fetch("/tan", {
                method: 'POST',
                body: formData,
                headers: { 'X-CSRFToken': csrftoken }
                })
            const json = await response.json();

            if (json.number) {
                tanBadge.textContent = "(" + json.number + ")";
                tanBadge.style.color = "red";
            } else {
                tanBadge.textContent = "";
                tanBadge.style.color = "";
            }

        } finally {
            setTimeout(fetch_now, 5000);
        }
    }
    setTimeout(fetch_now, 0);
    </script>
{% endif %}